// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.Models.Context;

#nullable disable

namespace SistemaAcademico.Migrations
{
    [DbContext(typeof(SistemaAcademicoDbContext))]
    partial class SistemaAcademicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CursoDisciplina", b =>
                {
                    b.Property<int>("CursosCursoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinasDisciplinaId")
                        .HasColumnType("int");

                    b.HasKey("CursosCursoId", "DisciplinasDisciplinaId");

                    b.HasIndex("DisciplinasDisciplinaId");

                    b.ToTable("CursoDisciplina");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("SubCategoriaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Disciplina", b =>
                {
                    b.Property<int>("DisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CargaHoraria")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDisciplina")
                        .HasColumnType("longtext");

                    b.HasKey("DisciplinaId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("SistemaAcademico.Models.SubCategoria", b =>
                {
                    b.Property<int>("SubCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("SubCategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("CursoDisciplina", b =>
                {
                    b.HasOne("SistemaAcademico.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursosCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademico.Models.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinasDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaAcademico.Models.Curso", b =>
                {
                    b.HasOne("SistemaAcademico.Models.SubCategoria", "SubCategoria")
                        .WithMany("Cursos")
                        .HasForeignKey("SubCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("SistemaAcademico.Models.SubCategoria", b =>
                {
                    b.HasOne("SistemaAcademico.Models.Categoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaAcademico.Models.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("SistemaAcademico.Models.SubCategoria", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
